### ISSUE TITLE
Internal Server Error for NGINX Setup

### ISSUE THREAD

**Issue by darksheer** [TheHive-Project/Hippocampe#51]
### Request Type
Bug
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.0.4
| OS version (client)       | MacOS
| Hippocampe version / git hash   | Latest
| Package Type              | From source
| Browser type & version    | N/A

### Problem Description
The NGINX process for fronting Hippocampe fails with internal server error

### Steps to Reproduce
1. Install hippocampe per docs
2. Install nginix / uwsgi per docs
3. Access the webserver http://ip/hippocampe

**Comment by treed593** [comment]
+1 I have seen this as well, but I had my install working and it stopped randomly working. I will see if I can get the Hippocampe Logs from the server

**Comment by treed593** [comment]
`
2017-12-24 02:00:55,953 :: services.modules.shadowbook.processFeed :: ERROR :: processFeed.main failed for shunlist_IP.conf, no idea where it came from
Traceback (most recent call last):
  File "/opt/Hippocampe/core/services/modules/shadowbook/processFeed.py", line 67, in main
    resMsearch = searchIntel.littleMsearch(source.coreIntelligence, source.typeNameESIntel, parsedPage)
  File "/opt/Hippocampe/core/services/modules/shadowbook/searchIntel.py", line 72, in littleMsearch
    res = es.msearch(body = req)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 1161, in msearch
    raise ValueError("Empty value passed for a required argument 'body'.")
ValueError: Empty value passed for a required argument 'body'.
2017-12-24 02:00:55,953 :: services.modules.shadowbook.processFeed :: INFO :: processFeed.main for shunlist_IP.conf end
2017-12-24 02:00:55,953 :: services.shadowbook :: INFO :: shadowbook.startJob end
2017-12-24 02:00:55,967 :: services.shadowbook :: INFO :: shadowbook.updateJob launched
2017-12-24 02:00:55,967 :: services.shadowbook :: INFO :: updating with status: done
2017-12-24 02:00:55,979 :: services.shadowbook :: INFO :: shadowbook.updateJob end
2017-12-24 02:00:55,980 :: services.shadowbook :: INFO :: shadowbook.manageJob end
`

**Comment by treed593** [comment]
`
--- no python application found, check your startup logs for errors ---
[pid: 1885|app: -1|req: -1/4] 10.0.0.136 () {48 vars in 801 bytes} [Sun Dec 24 02:25:10 2017] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.0 500) 2 headers in 83 bytes (0 switches on core 0)
`

**Comment by obikao** [comment]
Just ran into this. Check that all the requirements are installed 
`pip install elasticsearch Configparser netaddr flask python-dateutil apscheduler requests`
your permissions are correct and that app.py is set to executable
Lastly, try running it manually using python app.py if none of that works to identify any issue that may be preventing it from executing
