### ISSUE TITLE
Error 500 on MonitorRerssoucs

### ISSUE THREAD

**Issue by ppmartin-eh** [TheHive-Project/Hippocampe#55]
Bug 

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       |Ubuntu
| OS version (client)       | 10,.
| Hippocampe version |•  Git Latest commit f4d8807
| Package Type              | Binary
| Browser type & version    | All Browsers

### Problem Description
Unable to use the Monitor Ressource in the WebUI
Thet page monitorressopurce return an error 500

### Steps to Reproduce
Just click on the Home Page
No Monitor Source are dispalyed

### Complementary information
2018-03-24 17:36:34,605 :: services :: INFO :: monitorSources service requested
2018-03-24 17:36:34,608 :: services.modules.common.ES :: INFO :: ES.checkES launched
2018-03-24 17:36:34,620 :: services.modules.common.ES :: INFO :: ES.checkData launched
2018-03-24 17:36:34,623 :: services.modules.common.ES :: INFO :: ['sourceType']
2018-03-24 17:36:34,658 :: services.modules.common.ES :: INFO :: index hippocampe and type source exist
2018-03-24 17:36:34,668 :: services.monitorSources :: INFO :: monitorSources.main launched
2018-03-24 17:36:34,669 :: services.lastQuery :: INFO :: lastQuery.main launched
2018-03-24 17:36:34,670 :: services.sources :: INFO :: sources.main launched
2018-03-24 17:36:34,740 :: services.sources :: INFO :: sources.main end
2018-03-24 17:36:34,746 :: services.lastQuery :: INFO :: lastQuery.main end
2018-03-24 17:36:34,752 :: services.schedReport :: INFO :: schedReport.main launched
2018-03-24 17:36:34,762 :: services.sources :: INFO :: sources.main launched
2018-03-24 17:36:34,810 :: services.sources :: INFO :: sources.main end
2018-03-24 17:36:34,827 :: services.schedReport :: INFO :: schedReport.main end
2018-03-24 17:36:34,830 :: services.sizeBySources :: INFO :: sizeBySources.main launched
2018-03-24 17:36:34,832 :: services.sources :: INFO :: sources.main launched
2018-03-24 17:36:34,881 :: services.sources :: INFO :: sources.main end
2018-03-24 17:36:35,369 :: services.sizeBySources :: INFO :: sizeBySources.main end
2018-03-24 17:36:35,371 :: services.freshness :: INFO :: freshness.main launched
2018-03-24 17:36:35,381 :: services.sources :: INFO :: sources.main launched
2018-03-24 17:36:35,429 :: services.sources :: INFO :: sources.main end
2018-03-24 17:36:35,445 :: services.freshness :: INFO :: freshness.main end
2018-03-24 17:36:35,448 :: services.lastStatus :: INFO :: lastStatus.main launched
2018-03-24 17:36:35,471 :: services.lastStatus :: ERROR :: lastStatus.main failed, no idea where it came from...
Traceback (most recent call last):
  File "/home/thehive/Hippocampe/core/services/lastStatus.py", line 14, in main
    globalReport = bag.getLastJob()
  File "/home/thehive/Hippocampe/core/services/modules/jobs/BagOfJobs.py", line 108, in getLastJob
    report = self.matchResponse['hits']['hits'][0]['_source']
IndexError: list index out of range
2018-03-24 17:36:35,490 :: services.monitorSources :: INFO :: monitorSources.main end
2018-03-24 17:36:35,491 :: services :: ERROR :: monitorSources failed

**Comment by obikao** [comment]
Having the same issue. Try adding 

if 'link' in report:

to line 16 in lastStatus
